- name: Delete User
  hosts: servers
  become: true
  vars:
    users: ""

  tasks: 
    
    - name: Check for running processes for each user
      ansible.builtin.shell: "pgrep -u {{ user_to_delete }}"
      register: user_processes
      ignore_errors: true


    - name: Fail if users have running processes
      ansible.builtin.fail:
        msg: "User {{ user_to_delete}} has running processes: {{ user_processes.stdout_lines }}"
      when: user_processes.rc == 0

    - name: Check crontab for each user
      ansible.builtin.shell: "crontab -l -u {{ user_to_delete }}"
      register: user_crontab
      ignore_errors: true

    - name: Warn if crontab exists
      ansible.builtin.fail:
        msg: "User {{ user_to_delete }} has crontab: {{ user_crontab.stdout_lines }}"
      when: user_crontab.rc == 0

    - name: Ensure backup directory exists
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Backup home directories  
      ansible.builtin.command: >
        rsync -a /home/{{ user_to_delete }}/ {{ backup_dir }}/{{ user_to_delete }}/

    - name: Delete users
      ansible.builtin.user:
        name: "{{ user_to_delete }}"
        state: absent
        remove: true   # removes home directory

    